### PR TITLE
fix(workspace): exclude blib/, local/, vendor/ from file discovery (#3493)

### LINKED ISSUE #3493: [workspace] File discovery includes built artifact directories (blib/, local/, vendor/)
## Problem

Workspace file discovery does not exclude Perl built artifact directories, leading to duplicate symbol indexing when modules exist in both source form (`lib/`) and built form.

**Current exclusions:** `.git`, `.hg`, `.svn`, `target`, `node_modules`, `.cache`  
**Missing exclusions:** `blib/` (MakeMaker builds), `local/` (local::lib/cpanm), `vendor/` (carton)

**Evidence:**
- `crates/perl-workspace-ignore/src/lib.rs:13` defines `SKIPPED_DIRS` — missing these three
- A project using MakeMaker creates `blib/lib/MyModule.pm` (built copy of `lib/MyModule.pm`)
- Workspace index will load both, creating duplicate symbols `MyModule::foo` with two definitions
- Carton projects create `local/lib/perl5/` when dependencies are installed locally
- Issue: Users see multiple definitions in symbol search; cross-file resolution is ambiguous

**File locations:**
- `crates/perl-workspace-ignore/src/lib.rs` — `SKIPPED_DIRS` constant
- `crates/perl-workspace-discovery/tests/lib.rs` — test coverage

## Root Cause

The skip directory list was manually maintained without including Perl-specific build outputs. These directories are not part of typical VCS (git, hg, svn) or JavaScript (node_modules) workflows but are standard in Perl projects.

## Options

1. **Add three directories to SKIPPED_DIRS** — Add `"blib"`, `"local"`, `"vendor"` to the skip list. Risk: very low. Some projects may intentionally commit built artifacts, but this is rare and can be overridden via `.gitignore`. Effort: EASY.

2. **Make skip list configurable** — Extend LSP settings to allow custom skip patterns. Risk: moderate (requires settings design). Effort: MEDIUM.

## Recommendation

**Option 1** — Add the three directories. These are nearly universal in Perl projects and their presence indicates built/cached artifacts, not source. No downside to excluding them since users who want them indexed can remove them from `.gitignore`.

## Builder Spec

**File(s) to change:**
- `crates/perl-workspace-ignore/src/lib.rs:13` — Update `SKIPPED_DIRS` from 6 to 9 entries

**Test to add:**
```rust
#[test]
fn skipped_dirs_includes_perl_build_artifacts() {
    let expected = ["blib", "local", "vendor"];
    for dir in expected {
        assert!(
            is_skipped_dir_name(dir),
            "expected '{dir}' to be in SKIPPED_DIRS"
        );
    }
}

#[test]
fn discovery_excludes_blib_local_vendor() -> Result<(), Box<dyn std::error::Error>> {
    let tmp = tempfile::tempdir()?;
    let root = tmp.path();
    
    fs::write(root.join("lib/Foo.pm"), "package Foo;\n1;\n")?;
    fs::write(root.join("blib/lib/Foo.pm"), "package Foo;\n1;\n")?;
    fs::write(root.join("local/lib/perl5/Bar.pm"), "package Bar;\n1;\n")?;
    fs::write(root.join("vendor/lib/Baz.pm"), "package Baz;\n1;\n")?;
    
    let result = perl_workspace_discovery::discover_perl_files(root);
    
    // Should only find the source version, not the built/local copies
    assert_eq!(result.files.len(), 1);
    assert!(result.files[0].ends_with("lib/Foo.pm"));
    assert!(!result.files.iter().any(|p| p.contains("blib")));
    assert!(!result.files.iter().any(|p| p.contains("local")));
    assert!(!result.files.iter().any(|p| p.contains("vendor")));
    
    Ok(())
}
```

**Verify:**
```bash
cargo test -p perl-workspace-ignore -- skipped_dirs --exact
cargo test -p perl-workspace-discovery -- discovery_excludes
cargo fmt --all && cargo clippy -p perl-workspace-ignore -p perl-workspace-discovery
```

## Acceptance Criteria

- [ ] `blib/` directory is skipped by `is_skipped_dir_name()`
- [ ] `local/` directory is skipped
- [ ] `vendor/` directory is skipped
- [ ] `discover_perl_files()` excludes these directories and their contents
- [ ] Workspace index does not load duplicates from built artifact dirs
- [ ] All existing tests pass
- [ ] New tests document the three directories

## Scope

- **Crate(s):** perl-workspace-ignore, perl-workspace-discovery
- **Files:** `crates/perl-workspace-ignore/src/lib.rs`
- **Effort:** EASY (<1h)
- **Impact:** Eliminates duplicate symbol entries in large projects; cleaner workspace index

---
_Filed by scout agent. Builder-ready: no research needed._

### PR DESCRIPTION
**Pull request by EffortlessSteven**
## Summary

- Adds `blib`, `local`, and `vendor` to the `SKIPPED_DIRS` constant in `perl-workspace-ignore`
- `blib/` is the standard Perl build output directory (created by `make`/`Build`)
- `local/` is the `local::lib` install tree used for project-scoped CPAN deps
- `vendor/` is a common vendored-dependencies directory pattern
- Without these exclusions, workspace file discovery traverses built artifacts and vendored deps, creating duplicate symbol entries for every module installed under these trees

## Changes

- `/crates/perl-workspace-ignore/src/lib.rs`: `SKIPPED_DIRS` array size 6 → 9; 15 new tests covering `is_skipped_dir_name` and `path_contains_skipped_component` for each new entry; updated count assertion and "should not be skipped" list

## Test plan

- [ ] `cargo test -p perl-workspace-ignore` — 52 tests pass (was 43)
- [ ] `cargo fmt -p perl-workspace-ignore` — clean
- [ ] `cargo clippy -p perl-workspace-ignore --lib` — no issues
- [ ] New tests: `test_skipped_dir_name_blib_matches`, `test_skipped_dir_name_local_matches`, `test_skipped_dir_name_vendor_matches` and 6 path-level tests (at-root and nested for each new dir)

Closes #3493

### CODE REVIEW

**Comment by EffortlessSteven** [comment]
## Review finding: mislabeled PR

This PR's title and description claim to implement #3493 (exclude blib/local/vendor from file discovery) but the actual diff implements **security diagnostic for global SIG handler assignments** (PL602).

The code quality for the SIG handler feature is solid and passes standards review, but the metadata is wrong. This needs to be either:
1. Re-titled to match its actual content (SIG handler diagnostics)
2. Or the correct branch needs to be pushed for the workspace-ignore work

**The actual #3493 workspace-ignore fix was built separately** and may have been pushed to a different branch. Check `fix/workspace-ignore-blib-vendor-3493` branch.

**Comment by EffortlessSteven** [comment]
Replaced by #3637 — this PR was pushed to the wrong branch (release/0.12.3-prep instead of master). #3637 is the clean reimplementation from master.
