### PR TITLE
refactor(semantic): add read-only semantic query façade (#0000)

### PR DESCRIPTION
**Pull request by EffortlessSteven**
### Motivation

- Consumers currently stitch parser, semantic analyzer, pragma tracking, and optional workspace lookups directly which complicates incremental adoption. 
- Provide a small, stable, read-only integration surface that composes existing parser/semantic/workspace capabilities without changing semantic behavior. 

### Description

- Add a new `semantic_query` module at `crates/perl-parser/src/semantic_query.rs` exposing narrow façade types: `ResolvedSymbol`, `DefinitionLocation`, `VisibleImport`, `ParentChain`, and `EffectivePragmaState`. 
- Implement `SemanticQueryFacade` with read-only query methods: `new`, `resolved_symbol_at`, `definition_location`, `visible_imports`, `parent_chain`, `inherited_origin`, and `effective_pragma_state`. 
- Wire the façade into the public parser crate by exporting `pub mod semantic_query;` from `crates/perl-parser/src/lib.rs`. 
- Add an integration-style unit test `facade_exposes_read_only_queries` validating symbol resolution, imports, parent-chain, inherited-origin shape, and effective pragma features. 

### Testing

- Ran `cargo test -p perl-parser facade_exposes_read_only_queries` and the test passed. 
- Ran `cargo check --workspace --all-targets` and the workspace check passed.

------
[Codex Task](https://chatgpt.com/codex/cloud/tasks/task_e_69eb0077b68c8333b3ad3d962f730b79)

### CODE REVIEW

**Comment by EffortlessSteven** [comment]
## Deep Review: Architectural Layer Violation — Recommend Closing

**Verdict: Close this PR. PR #6031 is the correct implementation.**

### Root cause

`perl-parser` is a composition/facade crate. Its own CLAUDE.md states:
> "almost all logic lives in the upstream microcrates. Edits to … semantic logic belong in perl-semantic-analyzer"

`crates/perl-parser/src/semantic_query.rs` introduces semantic implementation logic directly in the composition layer:
- New `collect_visible_imports` AST walker (semantic logic — wrong layer)
- Direct instantiation of `SemanticAnalyzer`, `ClassModelBuilder`, `PragmaTracker` (reimplements the stack that `perl-semantic-analyzer` already encapsulates via `SemanticModel`)
- An independent `SemanticQueryFacade<'a>` type with a lifetime parameter and different constructor signature from #6031

### Conflict with PR #6031

PR #6031 adds the same facade in the correct crate (`perl-semantic-analyzer`) with proper delegation through `SemanticModel`. If both PRs merged, consumers of `perl-parser` would see two incompatible types:
- `perl_parser::semantic::SemanticQueryFacade` (from #6031, owned, no lifetime)
- `perl_parser::semantic_query::SemanticQueryFacade<'a>` (from this PR, lifetime-bound)

Same concept, incompatible APIs, different layers.

### Type conflicts (same concept, different shapes)

| Type | #6031 (correct layer) | #6032 (wrong layer) |
|------|----------------------|---------------------|
| `VisibleImport` | `module_name: String` | `module, imports: Vec<String>, location` |
| `DefinitionLocation` | struct with `uri: Option<String>` | enum `CurrentFile/Workspace` |
| `ParentChain` | `ancestors: Vec<String>` | `parents: Vec<String>`, `mro` field |
| `EffectivePragmaState` | wraps `PragmaState` | flat booleans |
| facade constructor | `build(root, source)` | `new(root, source, workspace_index)` |

### Recommendation

Close this PR. PR #6031 is approved with improvements. Some design ideas from this PR (enum `DefinitionLocation`, `mro` field on `ParentChain`) have been cherry-picked into fixes on the #6031 branch.

/label-receipt-write pr 6032 CLOSED reviewer-deep

**Comment by EffortlessSteven** [comment]
Closing: architectural layer violation — semantic implementation logic belongs in perl-semantic-analyzer (PR #6031), not in the perl-parser composition crate. See deep-review comment above for full analysis.
