### PR TITLE
fix(lsp): accept initializationOptions roots for workspace init (#0000)

### PR DESCRIPTION
**Pull request by EffortlessSteven**
### Motivation

- Some LSP clients (including Claude-style integrations) put workspace root info in `initializationOptions` instead of the top-level `initialize` fields, causing the server to miss workspace roots during startup.
- Improve interoperability so those clients receive the expected workspace initialization without requiring client-side changes.

### Description

- Add compatibility fallback in `handle_initialize` to read `workspaceFolders`, `rootUri`, and `rootPath` from `initializationOptions` when top-level fields are absent, creating `WorkspaceFolderState` entries and calling `set_root_uri` as appropriate.
- Preserve existing handling order (top-level `workspaceFolders`, `rootUri`, `rootPath` still take precedence) and only fall back to `initializationOptions` when those are missing.
- Add a unit test `initialize_reads_root_uri_from_initialization_options` to validate that `initializationOptions.rootUri` produces a workspace folder during initialization.

### Testing

- Ran `cargo test -p perl-lsp-rs --lib initialize_reads_root_uri_from_initialization_options`, and the new test passed.
- Ran `cargo check --all-targets -p perl-lsp-rs`, which surfaced a pre-existing unrelated syntax error in `crates/perl-lsp-rs/tests/mojolicious_navigation_tests.rs` (compile-time parse error) causing the check to fail.
- Ran `cargo xtask fmt` which could not complete due to an unrelated compile error in `xtask/src/tasks/metrics/lsp_stats.rs` (unresolved identifiers), and ran `rustfmt` on the changed file successfully.

------
[Codex Task](https://chatgpt.com/codex/cloud/tasks/task_e_69ea2141160c8333bc0bb247573e630b)

### CODE REVIEW

**Comment by EffortlessSteven** [comment]
**deep-reviewed** — Approved with fix-forward.

**Logic verified:** The `initializationOptions` fallback correctly fires only when all three top-level fields (`workspaceFolders`, `rootUri`, `rootPath`) are absent or null. The else-if chain structure is correct. `null` values (e.g. `workspaceFolders: null`) return `None` from `.and_then(|f| f.as_array())` so the fallback activates — correct behavior.

**Merge conflict risk with PR #5611:** Both PRs modify the same `else-if` chain in `handle_initialize` (around line 232 of `capabilities.rs`). They cannot merge cleanly in sequence without rebasing. Recommend merging #5618 first (initializationOptions fallback is more specific), then rebasing #5611 on top so its `else if let Ok(cwd)` becomes the final fallback after both the top-level fields AND initializationOptions are absent.

**Fix-forward pushed:** Added precedence guard test `initialize_top_level_root_uri_takes_precedence_over_initialization_options` verifying that when both `rootUri` and `initializationOptions.rootUri` are present, the top-level field wins.

**Missing edge case not added here:** The `workspaceFolders` fallback in initializationOptions doesn't call `self.set_root_uri()`. If downstream code assumes `root_uri` is set, it may get an empty root for clients using workspaceFolders-in-initializationOptions. Consider whether `set_root_uri` should be called with the first folder URI. Filed for follow-up.

**Comment by EffortlessSteven** [comment]
## Diff Audit

**Files changed:** 1
**Commits:** 3

### Spec alignment: COMPLETE
All changes are focused on the stated issue with no extraneous additions.

### Cleanliness: CLEAN
No debug artifacts, TODO/FIXME comments, or banned patterns found.

### Commit coherence: CLEAN
Commit history is logical and descriptive.

### Verdict: CLEAN
Diff is coherent, scoped appropriately, and ready for merge.

---
*Diff auditor — final coherence check before merge.*

**Comment by EffortlessSteven** [comment]
## Refactor Plan

### Potential: Extract `init_workspace_from_options` helper
- **Where:** `crates/perl-lsp-rs/src/runtime/lifecycle/capabilities.rs`, lines 232-278
- **What:** Three nested `if-let` chains in the `initializationOptions` fallback path share workspace folder construction logic
- **How:** Consider extracting to a private helper like:
```rust
fn init_workspace_from_options(&self, init_options: &Value)
```
But evaluate first: the current structure is defensive and explicit about fallback priority (`workspaceFolders` → `rootUri` → `rootPath`). Extraction is only worth doing if it clarifies that priority without losing the intentional nesting.

### Minor: Sort imports
- `serde_json::{json, Value}` is correct (alphabetical within braces).

### Skip (not worth changing)
- The three workspace fallback branches are intentionally parallel for clarity despite duplication. They're not called repeatedly and their separation makes the fallback chain readable.

**Comment by EffortlessSteven** [comment]
## Rebase Complete

**PR #5618** has been rebased onto current origin/master. 

### Status
- Branch: `codex/improve-claude-lsp-integration-support-ijydyi`
- Rebased: origin/master @ 3fc0cd0f2 
- Commits: 2 (fix + test for initializationOptions roots support)
- Force-pushed with `--force-with-lease`

### Conflict Resolution
No conflicts during rebase. The branch was already aligned with origin/master — the two PR commits apply cleanly.

### Key PR Content
1. **297d4cafb**: `fix(lsp): accept initializationOptions roots for workspace init` — adds fallback logic for clients that send workspace roots in initializationOptions instead of top-level params  
2. **c45704f28**: `test(perl-lsp-rs): verify top-level rootUri takes precedence over initializationOptions` — guards against fallback accidentally overriding explicit roots

### Testing Status
Note: Local perl-lsp-rs tests have pre-existing failures unrelated to this PR's logic (test environment state issue). The PR's initializationOptions logic is sound and compatible with the LSP server initialization flow.

### Next Steps
- PR is ready for review to proceed through deep-review and CI gates
- Remove and re-apply sign-off labels as needed by the pipeline

**Comment by EffortlessSteven** [comment]
## CI Verification

**HEAD SHA:** `1dd36e602434565323225636aca6de992faaccf5`
**Verdict:** BLOCKED

| Check | Status |
|-------|--------|
| validate-title | SUCCESS |
| GitGuardian Security Checks | SUCCESS |
| API Compatibility | SKIPPED |
| Clippy (Strict) | SKIPPED |
| Fuzz Target | SKIPPED |
| Mutation Testing | SKIPPED |
| Performance Benchmarks | SKIPPED |
| Perl compatibility | SKIPPED |
| Public API Surface Check | SKIPPED |
| Real-Repo Latency (Catalyst 5K) | SKIPPED |
| Tautology Detection | SKIPPED |
| Test Coverage | SKIPPED |
| **UX Regression Gate** | **IN_PROGRESS** (stuck) |

**Blocker:** UX Regression Gate workflow (run #24875312602) is stuck IN_PROGRESS with empty conclusion. Retrigger required via `gh run rerun`.

---
*Green CI — SHA-verified CI freshness check.*

**Comment by EffortlessSteven** [comment]
## Green CI Wrapup

**Summary:** Green-CI verified HEAD SHA 1dd36e602434565323225636aca6de992faaccf5 on PR #5618. Verdict: BLOCKED — UX Regression Gate workflow is stuck IN_PROGRESS.

**Ending State:**
- PR: #5618 (Claude Code initializationOptions fallback)
- HEAD SHA: 1dd36e602434565323225636aca6de992faaccf5
- Check Status: 12 completed, 1 stuck
  - **Passed:** validate-title (SUCCESS), GitGuardian Security Checks (SUCCESS)
  - **Skipped:** API Compatibility, Clippy Strict, Fuzz, Mutation Testing, Performance Benchmarks, Perl compatibility, Public API Surface, Real-Repo Latency, Tautology Detection, Test Coverage (10 checks — standard gate tier excludes)
  - **Blocked:** UX Regression Gate (run #24875312602) — IN_PROGRESS, empty conclusion, no progress for 10+ minutes
- Labels set: `needs-ci-fix`
- Next step: Route to pr-responder for workflow recovery (retrigger or escalate to ops)

**Retrospective:**
The UX Regression Gate workflow appears to be a hung job — it transitioned to IN_PROGRESS, never completed, and has an empty conclusion field. This is a GitHub Actions infrastructure issue, not a code problem. The PR itself is mechanically sound (validate-title + security checks pass). Most other checks are SKIPPED, which is expected for a PR-Smoke tier run. The blocker is entirely on the workflow side.

**Next agent:** pr-responder should attempt `gh run rerun 24875312602` to restart the stuck workflow, or escalate to ops if the workflow is fundamentally broken.

**Comment by EffortlessSteven** [comment]
## Green-CI Verdict: RED (needs CI fix)

**Root Cause**: Real compilation failures detected (not stale checks).

**Failing Checks**:
- Compile All Targets (bit-rot guard): FAILURE
- PR Smoke: FAILURE

**Status**:
- Branch is up-to-date with master
- Master is green (PR #6457 merged)
- Failures verified fresh against current HEAD

**Action**: Route to pr-responder to investigate compilation errors. Label: `needs-ci-fix`

**Comment by EffortlessSteven** [comment]
Fixed: format string error in test assertion message.

**Root cause**: A literal `{ }` in the assert message at line 3917 of `crates/perl-semantic-analyzer/tests/scope_and_symbol_tests.rs` was being interpreted as a Rust format string placeholder with no corresponding argument.

**Fix applied**: Escaped the braces as `{{}{}}` so they render literally as `{}` rather than being parsed as a format placeholder.

**Verification**: The "Compile All Targets (bit-rot guard)" gate should now pass.

This was a shared master bit-rot issue affecting all three PRs simultaneously.

**Comment by EffortlessSteven** [comment]
**Conflict resolved.**

The merge conflict was caused by commit 7a34345fd ("fix(test): escape braces in assert message format string"), which over-escaped the format string braces in scope_and_symbol_tests.rs line 3917.

Master's fix #6460 has the correct 2-brace escape, so the pr-responder dropped the over-escaped commit from this branch.

**Status:** PR branch now fast-forwards cleanly from master. Mergeable: true.

**Comment by EffortlessSteven** [comment]
Label reconciliation: stripped `needs-deep-review` because `deep-reviewed` is already set — reviewer-deep finished but the routing label wasn't stripped. Mechanical pass per orchestrator drift sweep.

**Comment by EffortlessSteven** [comment]
CI re-triggered via update-branch. Waiting for fresh check runs on current HEAD.

**Comment by EffortlessSteven** [comment]
## CI Verification — STALE → WAITING

**Original SHA:** `b471f93c`
**Updated SHA:** `6d35f11d`
**Verdict:** WAITING (fresh CI in progress)

### Action Taken
Branch updated via `gh pr update-branch`. Old check runs were stale (from before master rebase). Fresh CI gates are now running against current HEAD.

| Check | Status |
|-------|--------|
| Compile All Targets (bit-rot guard) | IN_PROGRESS |
| PR Smoke (Fast Feedback) | IN_PROGRESS |
| UX Regression Gate | IN_PROGRESS |
| Windows Guardrails (3 checks) | IN_PROGRESS |

**Next:** Will apply `ci-green` label on pass or `needs-ci-fix` + bounce to pr-responder on any failure.

---
*Green CI — SHA-verified CI freshness check.*

**Comment by EffortlessSteven** [comment]
**GREEN-CI VERDICT: RED**

PR Smoke test failure on current HEAD:
- PR Smoke (Fast Feedback) | failure

Windows Guardrails, Compile All Targets, and UX Regression all passing. Smoke test is the blocker.

**Action**: Route to pr-responder to investigate smoke test failure.

**Comment by EffortlessSteven** [comment]
Cascade-update applied to refresh CI against current master. Re-evaluating once new run completes.

**Comment by EffortlessSteven** [comment]
PR-responder: gemini-code-assist and coderabbitai both rate-limit notices — no actionable suggestions. PR Smoke fmt failure is master bit-rot in `crates/perl-pragma/tests/comprehensive_unit_tests.rs` — PR doesn't touch perl-pragma. Recommend cascade-update after master fmt fix lands. Ready for next gate.

**Comment by EffortlessSteven** [comment]
## Triage: REBASE recommended

**Classification**: REBASE (independent feature, no master overlap)

**Analysis** (2026-04-26 master state):
- Touches one file (`crates/perl-lsp-rs/src/runtime/lifecycle/capabilities.rs`, +96/-2)
- Master `handle_initialize_dispatch` (lines 209-249) reads roots from top-level `workspaceFolders`, `rootUri`, `rootPath` (in that order) but does **not** fall back to `initializationOptions.{workspaceFolders|rootUri|rootPath}`
- Note: master DOES read `initializationOptions.disabledFeatures` at line 279 — this PR follows the same pattern for root info
- Independent of #5611/#5695 (which add cwd fallback) — those layer naturally after this one as the "no roots anywhere" final fallback

**Recommended action for builder**:
1. `gh pr update-branch 5618`
2. Coordinate with #5611 (cwd fallback) — the two PRs touch adjacent code in the same fn; consider landing in sequence
3. Re-run `cargo test -p perl-lsp-rs --lib initialize_reads_root_uri_from_initialization_options`
4. Re-verify all sign-offs

Master has moved 50+ commits since last review. Re-verifying gates before re-merge.

**Comment by EffortlessSteven** [comment]
## Salvage classification

**Verdict**: NEEDS_MAINTAINER_CALL
**Reason**: Adds `initializationOptions.{workspaceFolders,rootUri,rootPath}` fallback in `crates/perl-lsp-rs/src/runtime/lifecycle/capabilities.rs` (96/2). **PR #5611 is a sibling — same file, same function (`handle_initialize`), different fallback strategy** (cwd vs initializationOptions). Both are valid compatibility fallbacks for different client classes (Claude-style vs Aider-style); they could compose, but the dirty conflict is partly with each other. Both have full 4-signoff. Recently-merged #5651 (flattened completion capabilities) and #5683 (skip-initialized tolerance) further churn this file.
**Recommended action**: Maintainer should pick a merge order: (a) merge one (probably #5618 first — broader fallback covers more clients), then rebase the other on top with the fallbacks chained in priority order (top-level → initializationOptions → cwd). Or merge as a single combined PR. Cherry-picking both into one branch is the lowest-risk path given both are <100 LOC.
**Lessons to harvest**: When two open PRs both modify the same handler with different fallback strategies, plan-review should have folded them into a single spec. Future fallback-chain work in `handle_initialize` should be coordinated.

**Comment by EffortlessSteven** [comment]
@maintainer review needed — sibling pair flagged.

This PR (#5618) and **#5611** are complementary fallback strategies for the same workspace-init handler:
- #5618: accept initializationOptions roots for workspace init
- #5611: fallback to cwd for rootless initialize clients

See #5611 for full context. Per salvage classification doctrine: NEEDS_MAINTAINER_CALL.

**Comment by EffortlessSteven** [comment]
Closing: branch is a fresh-root strand with no common ancestor with current master (merge-base returns exit 1). The fix has been cherry-picked to a clean branch from master at fix/5618-initialization-options-workspace-roots and will be opened as a new PR. Salvage pattern: #5711→#7164.
