### PR TITLE
fix(perl-position-tracking): clamp UTF-16 mid-surrogate positions (#0000)

### PR DESCRIPTION
**Pull request by EffortlessSteven**
### Motivation
- Fix LSP UTF-16 position mapping that advanced past supplementary characters when a requested UTF-16 column landed inside a surrogate pair, producing offsets inconsistent with other UTF-16 conversion helpers.

### Description
- Clamp in-surrogate UTF-16 positions in `PositionMapper::lsp_pos_to_byte` to the start of the code point (matching `utf16_line_col_to_offset`) and add a focused regression test `test_utf16_positions_clamp_mid_surrogate_to_char_start` for the string `"a😀b"`.

### Testing
- Ran `cargo test -p perl-position-tracking` (all tests passed), `cargo check --all-targets -p perl-position-tracking` (passed), `cargo clippy -p perl-position-tracking --all-targets -- -D warnings` (passed), and `cargo xtask fmt` (ran); `just pr-fast` is not available in this environment.

------
[Codex Task](https://chatgpt.com/codex/cloud/tasks/task_e_69eaa05fa954833385161e44b178c4f3)

### CODE REVIEW

**Comment by EffortlessSteven** [comment]
**Codex review**: Coordinated with #5754 and #5753 on UTF-16 surrogate boundary handling. Different crates (perl-position-tracking, perl-symbol). No merge needed; independent changes but part of same semantic fix family. Cross-link in final merge notes.

**Comment by EffortlessSteven** [comment]
deep-review: APPROVED with no changes needed.

**Verified:** The new surrogate-clamp logic in `PositionMapper::lsp_pos_to_byte` is correct. For text `a😀b` with `pos.character=2` (mid-surrogate), the old code would advance `byte_offset` past the emoji (returning byte 5), while the new code computes `next_utf16 = 1+2 = 3 > 2` and breaks early, returning byte 1 (start of emoji). This matches the existing behavior in `utf16_line_col_to_offset` in `convert.rs`. The added test covers the specific surrogate-split scenario. Position 3 (after the full surrogate pair) is also unaffected since `next_utf16 = 3 <= 3` continues correctly.

**Logic verified:** Consistent with the `convert.rs` behavior where mid-surrogate columns clamp to the code point start (see line 63: `up < col && col < up + ch.len_utf16()` returns `offset + bi`, i.e. the start of the character).

**Comment by EffortlessSteven** [comment]
## Diff Audit — CLEAN

**Files changed:** 1
**Commits:** Coherent linear history
**Tests:** All passing

### Spec alignment: COMPLETE
All acceptance criteria implemented; diff matches issue scope.

### Cleanliness: CLEAN
No artifacts (TODO, FIXME, debug prints in production code).
No scope drift; files belong to this PR's issue.
Commit messages are clear and follow pattern.

### Commit coherence: CLEAN
Linear history with proper feature/fix/test commits.

### Verdict: CLEAN
Cumulative diff is coherent, clean, and ready for merge.

---
*Diff auditor — final coherence check before merge.*

**Comment by EffortlessSteven** [comment]
## CI Verification

**HEAD SHA:** `0bbbd994e3b3f08e5b78f99eb088b7e1d04599fb`
**Verdict:** RED

| Check | Status |
|-------|--------|
| Draft PR guard | PASS |
| validate-title | PASS |
| Preflight — is this SHA latest? | PASS |
| PR Smoke (Fast Feedback) | PASS |
| Compile All Targets (bit-rot guard) | PASS |
| Windows Guardrails (compile) | PASS |
| Windows Guardrails (module-separator-regressions) | PASS |
| Windows Guardrails (sandbox-fail-closed) | PASS |
| GitGuardian Security Checks | PASS |
| UX Regression Tests | PASS |
| **CI Gate (Merge-Blocking)** | **FAIL** |

### Blocking Failures

**clippy_full** — Linting failures detected in the workspace
**lsp_tier_b** — LSP tier-b tests failed

Both are required to pass before merge. CI ran fresh on current HEAD (0bbbd99) with no stale results.

---
*Green CI — SHA-verified CI freshness check. Failures are genuine, not cached.*

**Comment by EffortlessSteven** [comment]
## Green CI Wrapup

**Summary:** Green-CI verified PR #5755 on current HEAD. CI is genuinely RED (not stale): 2 blocking failures (clippy_full, lsp_tier_b) need pr-responder fix. Set `needs-ci-fix` label.

**Ending State:**
- PR checked: #5755 (`fix(perl-position-tracking): clamp UTF-16 mid-surrogate positions`)
- HEAD SHA: `0bbbd994e3b3f08e5b78f99eb088b7e1d04599fb`
- CI status: FAIL (gate ran fresh, not cached)
- Blocking failures: clippy_full (linting), lsp_tier_b (LSP tier-b tests)
- Passing checks: 10/12 (Draft guard, validate-title, Preflight, PR Smoke, Compile All, Windows Guardrails x3, GitGuardian, UX Regression)
- Labels: Added `needs-ci-fix`; PR already had codex, deep-reviewed, review-reviewed, maintainer-pr-reviewed, diff-audited

**Retrospective:**
CI Gate took 20 minutes to run (970s merge_gate tier) and failed cleanly with two named blockers rather than timeouts or cascades. The failures are genuine logic/lint issues on the current HEAD, not stale cached results from an earlier push. One surprise: git revision errors ("fatal: Needed a single revision") appeared in the logs 5 times mid-execution but didn't stop the gate — xtask continued and produced usable output anyway. This is worth watching for future silent failures.

**Breadcrumbs for pr-responder:**
- Route to pr-responder immediately; this is non-mechanical (failing tests, not just format)
- Failures are linting (clippy_full) + LSP tier-b tests, not stale checks
- PR has 5 existing sign-offs (deep-reviewed, review-reviewed, maintainer-pr-reviewed, diff-audited, codex) — all prior gates passed
- CI confidence: HIGH — fresh run, no timeouts, clear failures
- Next: pr-responder fixes clippy + lsp_tier_b, then green-ci re-runs

**Comment by EffortlessSteven** [comment]
## Green-CI Verdict: RED (needs CI fix)

**Root Cause**: Real compilation failures detected (not stale checks).

**Failing Checks**:
- Compile All Targets (bit-rot guard): FAILURE
- PR Smoke: FAILURE

**Status**:
- Branch is up-to-date with master
- Master is green (PR #6457 merged)
- Failures verified fresh against current HEAD

**Action**: Route to pr-responder to investigate compilation errors. Label: `needs-ci-fix`

**Comment by EffortlessSteven** [comment]
Fixed: format string error in test assertion message.

**Root cause**: A literal `{ }` in the assert message at line 3917 of `crates/perl-semantic-analyzer/tests/scope_and_symbol_tests.rs` was being interpreted as a Rust format string placeholder with no corresponding argument.

**Fix applied**: Escaped the braces as `{{}{}}` so they render literally as `{}` rather than being parsed as a format placeholder.

**Verification**: The "Compile All Targets (bit-rot guard)" gate should now pass.

This was a shared master bit-rot issue affecting all three PRs simultaneously.

**Comment by EffortlessSteven** [comment]
**Conflict resolved.**

The merge conflict was caused by commit eb71373ca ("fix(test): escape braces in assert message format string"), which over-escaped the format string braces ({{{{ }}}} instead of {{ }}) in scope_and_symbol_tests.rs line 3917.

Master's fix #6460 has the correct 2-brace escape, so the pr-responder dropped the over-escaped commit from this branch.

**Status:** PR branch now fast-forwards cleanly from master. Mergeable: true.
